### ISSUE TITLE
error in configuring foxbms at "4.1.2.7. Testing the Project Setup"

### ISSUE THREAD

**Issue by rud90** [foxBMS/foxbms#4]
22:40:51 **** Incremental Build of configuration configure for project foxbms ****
python tools/waf configure 
python: can't open file 'tools/waf': [Errno 2] No such file or directory

22:40:51 Build Finished (took 499ms)

Hi, may I know what is the issue?
Thanks.

<img width="248" alt="foxbms_configure" src="https://user-images.githubusercontent.com/58696095/70444859-829e7380-1ad5-11ea-827d-a660fa112b89.PNG">

**Comment by foxBMS** [comment]
Dear @rud90,

On some machines there seem to be a problem with Eclipse workspaces.

Basically the problem is, that the Eclipse workspace is e.g. ``C:\users\<user>\documents\foxbms\.ws`` In order to run the build toolchain the eclipse projects are setup to run ``pyhton tools\waf <some argument>`` in ``C:\users\<user>\documents\foxbms``. In order to run this command, the build directory needs to be set to ``${workspace_loc}/../``.
![builder-type](https://user-images.githubusercontent.com/24648128/75960018-9df40180-5ebf-11ea-8590-a77a21cfef35.png)
On some machines, it seems that Eclipse is not possible to correctly resolve the relative path ``${workspace_loc}/../`` and this is why python then (correctly) complains, that the files ``tools/waf`` does not exist.

Since our latest release [v1.6.4](https://github.com/foxBMS/foxbms/releases/tag/v1.6.4) we provide an experimental VS Code setup, to overcome problem of a non functional Eclipse workspace. The VS Code setup is found [here](https://github.com/foxBMS/foxbms/tree/v1.6.4/tools/vscode). However this VS Code setup is experimental and should only be used in cases where setting up an Eclipse workspace fails.

Sorry for the inconvenience and best regards,
The foxBMS Team
