### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by mvenkat27** [foxBMS/foxbms#8]
![image](https://user-images.githubusercontent.com/48689586/99259327-1f0ae300-281a-11eb-96b4-42f81e71e289.png)
[](url)

I could not able to build the software in eclipse

**Comment by foxBMS** [comment]
Dear @mvenkat27,

would you please verify that you are using python3.6 or greater.
The waf unpacking directory starting with ``waf-*`` instead of ``waf3-*`` indicates that you are using some Python 2 version.

foxBMS uses f-strings in its python scripts and these are only supported in python versions greater 3.6 (see also #2).

Best regards,
The foxBMS Team
